---
title: "HR Data Exploratory Analysis Script"
date: "Summer 2024"
output: html_document
---


# Setup

```{r}
#load needed packages. make sure they are installed.
library(here) #for data loading/saving
library(dplyr)
library(skimr)
library(ggplot2)
```


Load the data.

```{r}
#Path to data. Note the use of the here() package and not absolute paths
data_location = here::here("data","processed-data","HRprocesseddata.rds")
#load data
myhrdata = readRDS(data_location)
```


## HR Data Exploration Through Tables


```{r}
col_names = names(myhrdata)
num_columns = 3   

num_rows = ceiling(length(col_names) / num_columns)

summary_matrix = matrix(col_names, nrow = num_rows, byrow = TRUE)

summary_df = as.data.frame(summary_matrix)


print(summary_df)
#Save to file
summarytable_file = here("results", "tables", "HRvariablestable.rds")
saveRDS(summary_df, file = summarytable_file)

```

## Data Summary

Basic summary of data.
```{r}
summary_df = skimr::skim(myhrdata)
print(summary_df)
# save to file
summarytable_file = here("results", "tables", "HRsummarytable.rds")
saveRDS(summary_df, file = summarytable_file)
```


## Gender Table

```{r}

summary_df = myhrdata %>%
  count(Gender) %>%
  mutate(`Total Count` = n,
         `% of Total` = (n / sum(n)) * 100) %>% #creating new column for percentage of total
  select(Gender, `Total Count`, `% of Total`) #selecting only 3 variables

print(summary_df)
# save to file
summarytable_file = here("results", "tables", "HRgendertable.rds")
saveRDS(summary_df, file = summarytable_file)
```


## Tenure Distribution

Visualizing tenure to find distribution.
```{r}
p1 = myhrdata %>%
  ggplot(aes(x = YearsAtCompany)) +
  geom_histogram(binwidth = 1, boundary = 0.5, fill = "gray", color = "black") +
  labs(x = "Tenure", y = "Count") + 
  theme_minimal() 

print(p1)

figure_file = here("results", "figures","tenure-distribution.png")
ggsave(filename = figure_file, plot=p1)
```

## Distribution of Tenure

```{r}
p2 = myhrdata %>%
  ggplot(aes(x = TenureCategory)) +
  geom_bar(fill = "gray", color = "black") +
  labs(x = "Tenure", y = "Count", title = "Distribution of Tenure Categories") + 
  theme_minimal()

print(p2)

figure_file = here("results", "figures","tenure-category.png")
ggsave(filename = figure_file, plot=p2)
```


## Education vs Monthly Income

```{r}
p3 = ggplot(myhrdata, aes(x = Education, y = MonthlyIncome)) +
  geom_boxplot(fill = "gray", color = "black") +
  labs(x = "Education", y = "Monthly Income", title = "Boxplot of Monthly Income by Education") + 
  theme_minimal()


print(p3)

figure_file = here("results", "figures","income-education.png")
ggsave(filename = figure_file, plot=p3)
```

## Age vs Attrition

```{r}
p5 = ggplot(myhrdata, aes(x = Age, fill = Attrition)) +
  geom_histogram(binwidth = 1, position = "dodge") +
  scale_fill_manual(values = c("No" = "grey", "Yes" = "#595959")) + #selecting bar colors
  labs(title = "Age vs Attrition", x = "Age", y = "Count") +
  theme_minimal()

print(p5)

figure_file = here("results", "figures","age-attrition.png")
ggsave(filename = figure_file, plot=p5)
```


```{r}
p4 = ggplot(myhrdata, aes(x = Department, fill = Attrition)) +
  geom_bar(position = "dodge", color = "black") +
  scale_fill_manual(values = c("No" = "grey", "Yes" = "#595959")) + #selecting bar colors
  labs(title = "Department vs Attrition", x = "Department", y = "Count") +
  theme_minimal()

print(p4)

figure_file = here("results", "figures","department-attrition.png")
ggsave(filename = figure_file, plot=p4)
```


